# Generated by Django 4.2.3 on 2023-07-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
