# Generated by Django 4.2.3 on 2023-07-26 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qes_Num',
            fields=[
                ('qesnum_id', models.AutoField(db_column='qesnum_id', primary_key=True, serialize=False)),
                ('default_que_num', models.IntegerField()),
                ('situation_que_num', models.IntegerField()),
                ('deep_que_num', models.IntegerField()),
                ('personality_que_num', models.IntegerField()),
                ('total_que_num', models.IntegerField()),
                ('form_id', models.ForeignKey(db_column='form_id', on_delete=django.db.models.deletion.CASCADE, related_name='qes_num', to='forms.form')),
            ],
            options={
                'db_table': 'qes_num',
            },
        ),
    ]
