# Generated by Django 4.2.3 on 2023-07-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='career',
            field=models.CharField(default='신입', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='resume',
            field=models.CharField(max_length=20000),
        ),
    ]
