# Generated by Django 4.2.3 on 2023-07-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speak_to_chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gptanswer',
            name='recode_file',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='speak_to_chat.question'),
        ),
        migrations.AlterField(
            model_name='gptanswer',
            name='gptanswer_id',
            field=models.AutoField(db_column='gptanswer_id', primary_key=True, serialize=False),
        ),
    ]
