# Generated by Django 4.2.3 on 2023-07-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisper', '0002_remove_voicefile_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicefile',
            name='gpt_answer',
            field=models.TextField(blank=True),
        ),
    ]
